{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-secrets",
    "namespace": "demo-rig-and-barter",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-secrets",
        "namespace": "demo-rig-and-barter",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "mysql_root_password": "AgDq0KjF7K8PoRGoyuSmNyntJnO+z73qYSyjmfXrPsVi1r908eg7ksV8JqkpINcK546/70NpZPL/9qQ1gm/AX8QeWdHVlMkO3XL9PjcVOo9rHAPtbXa3c5P32YB9XwFsJljXh8rHHkpedz6tu+x2UvCSK1U6xkNMxgV0LaLd1n1GqX8+rt9QDiKD/VYY5bmDEo3ssqv8MT6JBKHrIVkydEGaJ0m6VKEQC8058H3ZG+3FYmMJy2U6fZX+jYd1wyXU4+jMmC35XGbWadLKYv1FZnACR2U8G9Eap4j4/MhMQn48Fpx4M7N1TzG7lF+20KKwoIVDXZ+Kf6km9ocFu/vSTWTvqLeM4QCAOAa69J/5wDffO5UJeGPflVkIkOVjFsFvtmt0YjE4UoN1Ru96290W04QXQLx9dOvnB2dqnMAVP0Fo0oPqTSqSdUF7aXBCtK4hThHd5Hxp1HtE1WVYVsi1Mi8YNE/p+MjyoRPPq2agp5p5/VmhQiFc4JzPuqoeefajborPO5VQO+8NSNjWIDfQYBJnxwrdmtqKoeu80qS2R8gXGvYC1ImdZKhliItk7VFqzo+5UzP/bCFbRgo6/Q7oe9GlLFMccGhntYJEMvvSI7xD9QcJSijSqGuj3k2zA6R6JBOCYrM/vXaZZWWIx3IdhlDEFgTxQZV/4EGxFBSEYLDQ1oStOEvYMn1UtoqW2BrBZnq6xEM+B0HPVQtKhgbvvQ==",
      "mysql_root_username": "AgCldW/6mssImf/5Wt+kjQVlOnbeT4g1hjLKofs3gdLwCMxoy2W/sHPWPmWTcZBwAaPG8bO/j146gxiBu8oRtY0f7wL/+NRwvyZ7UjMIAYztlumChOdcOVRY+BFbBJij2J1x4cix5d48biAi+u4Qs8HquKXYkzcOucEAlZY63dYWK7Oeg0fTP9vl4FVQTTv24wK0YN0z5WLn+4r/q8mkDpEm2iECpRlIBnO1eNJMHJNZ1fYGZIhSI+WKnvK3V/ky5KtcNsKlyaSK+ZnD8WZyXID7Ba5jThA4Fv8XhoZaW5rh6tjBRXc44/IfRDMJT6UiFgB+/Sth3JIv0vj7hhag8Ug/kdxLogLZfHGR6rxZvdQdAGqlGeDCMzUxG2gQol+Sb6d0+E5YClJNGk7Q2z2To1i6YOfGBb96TA8onPNG4K4I/rEBcSiEaQSU8Z+Le0eqjF8WW6v9nCrkzzBdifjdjg4NB8dxlQg4WU8R/RggZdNZ/Tv58xESoBCYljfrS8n67ezfKc+d/Nm10ZN5jybeNOMX6pkabNsGOF83zbNPxwasV5OI9b5usYig65tD7VA2shJHSNRm7/nXO068KkNRJrQNBJwldW1Y22q2C6BaX0O9AfaJDfvvNw778v+enRukdD1xt2dzYq8aNno1lXw/OVzNQ2SeqgI4w5KUDDtLNP4u8c5G2aVQljQk2NUOyzpuCLZOO80y"
    }
  }
}
