server-port:8080
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8180/realms/rig-and-barter-realm


#spring.security.oauth2.client.registration.keycloak.client-id=rig-and-barter-client
#spring.security.oauth2.client.registration.keycloak.client-secret=dE7irq4Kj44QbiftdLvi1q9tHLpWMlRL
#spring.security.oauth2.client.registration.keycloak.scope=openid, profile
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirectUri=http://localhost:8180/login/oauth2/code/{registrationId}
#
#spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8180/realms/rig-and-barter-realm/protocol/openid-connect/auth
#spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/rig-and-barter-realm/protocol/openid-connect/token
#spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:8180/realms/rig-and-barter-realm/protocol/openid-connect/userinfo
#spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8180/realms/rig-and-barter-realm/protocol/openid-connect/certs
