{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "keycloak-mysql-secrets",
    "namespace": "demo-rig-and-barter",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "keycloak-mysql-secrets",
        "namespace": "demo-rig-and-barter",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "mysql_password": "AgCQ+Y9xF94hbpXUrnFdJSKiX9dK8yHG0y959SzzVMa95zp+MAzINTr6uC3f5cw9gu1C+a7BmnRgRcOdH41+C77wHSoTrM1pU2g1ZU0iyfl12/XfvX9ffeBAgIYbkjlx6sFEcZO2n3GT2DeRx26KLJn+odkNaNbn7YCIecHnmKfgDFGiP3Dk5BTOAVLKCHc9c8L3rjxxRI8WPiYy5Lh1GQCBvxTdyEmWgUPbsKFVQpbrmysyhttef04fV7BMyCNIg7rjnRus2DwnKVVUbGPyK0pb4k95UEwiTuApHGdY6mjjcKhTj2EfmdVKxSvmTwgJp6c1EyKyVVXR2xFK1u/PswtkHMDVvZ86dc5UDAfK4fUZ8GcideT7OaWorWvPbDPIeFgfwzqXPLYy5i1BTuVsFbAy4g1lmxqugrCFcSJxgrGREoEl+2xuHAK9m2RVPINKNe1m74TKvTWN//XYfYcpWzq96I/fP983MJh9zfmyck4DMuvz6H0H8jzp/Rh2isZRGIUyoFdZwUrhB74qh4zifFjrpFCn0lFxXOFt7xhmQ+GGPS+ZhR4e8I8fRzM8PpTQ2oRENiQ9CPcvyINI/Kyhv4QvQQoRNG7Qbnp+cAVawLgABfLWOs+JT/4p1JHs9rnZj3G7wZfniI6wPmqj8NMp26KJdepDfJsGaKZORov9UK/U+KS854071ScwKAyNPCn3RiUwP4pK9Q7v64zlD6znCks=",
      "mysql_root_password": "AgBJfZTl1D0lqKu7LROckF6dxgZvYyPGeHB5Y22IdDIubxDMbA2TJdONHWiLbeuwY11bp2gN6ljMRaEzUZMbeCSICuAh3G+2ecwyWcObvcYPhC0K1QFUl9hZ5iJ8Xqv9mJ7qGCHv6mxQ4H58B4c93mB6hMogjBB0ZREs/sQDnen96uC/UVQMjeU8oWMmy08BCkvw2/lLku/iU/kq8OjmQDG1BZtqIDnJw8BL9QQMKLKIyIDP9IASec8dm0TP80yFHsSgexB4IYm3JP4ZRfi7SsZRqb0MRoIFE/Lm6M4tPhAdEUFH+liojStS5ct02eduC44Q3RcuWX3HpRXos3ZWGP/QmUrt1ccHr9CKLAgJ8aSQXLJmqlgzo9vlSW2lsBed/xVozs/l5/++8vArOPOboIuEQZEcsxuiDTPEg7rDmOlogjKLQgvvSuEw7x63WpUa6aji+KvrirAWzF4tVy/jrZpOmQepU2Ee8JUclGW71xc1vOfURTkrGaKSnpRNrL1oRhKC8E8Tvv2o4wdh9qsWo1s8WHkugx1E4Rds1+uidJycGxc0MG8ay8ysaGr/vaW4huxVFp8dR7I5RxtH8D2Spd4FeagP4L2IE3IoVCCpcyuee0MhHJ2ISEZjyGxRkOvj4tqk+OohH4p4yRBnll1KWBt6Bn8t1d+UNusWYB8fqMYgEXRjBPa+aw0UrZ9V024YCnhKU/oj",
      "mysql_user": "AgBCafHnTJy/xHb0JZxSXcpJ9kXcdvkuZr+4sbGScbUJ+3F+1gK9LWeqtvX0dvIuKnggwdjAMDaBZKEte4iMABPszsbL7MQgBvdyTV/uk12dxmsCOhm/+7mbZ1GHxinQongsywThKedfQUh/Fn1bc9z5WfpMUTBCJBiWKDYbKRPd2i9/KLGn9FJ7QM0n6N8Z2elSX/fIFEuqij8s22RLN3TDZmixgGZij96LN0cPRiVc0GUCTU/b/zIMAFV2Ciai7wViwUjQaNm4K907zsHTXNVtxl+53qsxxr5MUbuxDvrlALqdAXVDqHvast95zztB2t/fYimTiHgKzlgpr8EdOmoyRtCnIXJrm3SOhIn+7kqOUca+qbqCm1YKrOtW2GExraqZHQe7bY/ZgN1jT9roZU/ASjJWy7cSi4bgcoMcHfNfCadUlWFV8wO48hEyFDiROLzqrLGN4GNEVI7i1/MGwPRk4rNQYKuiCjoeEt1ezejlNSrkuTrhMeTysOurbY2hI2YKjHGO1iBm04WDFqtA1NDRjYaKwCnWefMk3Qmj54PnqPnCR2AJDQeABegWkkblpCt3VjgBL8scr7QE52qe3x70cnGTb8GdWAdlPMNrmrotPvRsATMM2hNvisfxkTI3MSpJSV8G5thXqJ6JZDcRX4f8OO+D+Yzf/l6Wc6hmE6Y/T9nNDmo0ngzgMeQgIapQriTuxmmspBATvQ=="
    }
  }
}
