---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: demo-rig-and-barter
data:
  aws_access_key: QUtJQVFSQUhURDI2RVRMS080SFk=
  aws_secret_key: YnRDWXBvS2VxbzJsRXN1eEtpdlExYm5nYVdIZ2xUV09jVmNQb3dxUQ==