---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: demo-rig-and-barter
data:
  db_user: cmFiYWRtaW4=
  db_password: em4yeCY5U1BQVW0lWWtn
  keycloak_admin_username: cmFiYWRtaW4=
  keycloak_admin_password: em4yeCY5U1BQVW0lWWtn
  keycloak_admin_client_secret: TFlkTW02eGdXTXlzOTZIMklVYkR2ZFdpY2RlWGI4eW4=
  rb_keycloak_admin_client_id: YWRtaW4tY2xp
  rb_keycloak_admin_client_secret: cE5lUU9FSDcwakZvYTJyalF3R1VERkY3VWgxY2pkeWw=