apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-service
  namespace: dev-rig-and-barter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-service
  template:
    metadata:
      labels:
        app: component-service
    spec:
      containers:
        - name: component-service
          image: cjshore1996/dev-component-service:latest
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
                  name: common-config
            - name: RB_EVENT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER
                  name: common-config
            - name: RB_EVENT_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER_URL
                  name: common-config
            - name: RB_STORAGE_DOCUMENT
              valueFrom:
                configMapKeyRef:
                  key: RB_STORAGE_DOCUMENT
                  name: component-service-config
            - name: RB_STORAGE_FILE
              valueFrom:
                configMapKeyRef:
                  key: RB_STORAGE_FILE
                  name: component-service-config
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodb_connection_string
                  name: component-service-secrets
            - name: MINIO_URL
              valueFrom:
                configMapKeyRef:
                  key: MINIO_URL
                  name: common-config
            - name: MINIO_BUCKET-NAME
              valueFrom:
                configMapKeyRef:
                  key: MINIO_BUCKET-NAME
                  name: component-service-config
            - name: MINIO_ACCESS-KEY
              valueFrom:
                secretKeyRef:
                  key: minio_access_key
                  name: minio-secrets
            - name: MINIO_SECRET-KEY
              valueFrom:
                secretKeyRef:
                  key: minio_secret_key
                  name: minio-secrets

      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: component-service
  namespace: dev-rig-and-barter
spec:
  selector:
    app: component-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-service-config
  namespace: dev-rig-and-barter
data:
  RB_STORAGE_DOCUMENT: "mongodb"
  RB_STORAGE_FILE: "minio"
  MINIO_BUCKET-NAME: "rb-component-images-dev"

