apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-service
  namespace: rig-and-barter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-service
  template:
    metadata:
      labels:
        app: component-service
    spec:
      containers:
        - name: component-service
          image: cjshore1996/dev-component-service:latest
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
                  name: common-config
            - name: RB_EVENT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER
                  name: common-config
            - name: RB_EVENT_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER_URL
                  name: common-config
            - name: RB_STORAGE_DOCUMENT
              valueFrom:
                configMapKeyRef:
                  key: RB_STORAGE_DOCUMENT
                  name: component-service-config
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodb_connection_string
                  name: component-service-secrets
            - name: SPRING_CLOUD_AWS_REGION_STATIC
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_AWS_REGION_STATIC
                  name: listing-service-config
            - name: SPRING_CLOUD_AWS_STACK_AUTO
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_AWS_STACK_AUTO
                  name: listing-service-config
            - name: AWS_S3_BUCKET-NAME
              valueFrom:
                configMapKeyRef:
                  key: AWS_S3_BUCKET-NAME
                  name: listing-service-config
            - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_access_key
            - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_secret_key
          volumeMounts:
            - mountPath: /data/component-service
              name: component-data
      volumes:
        - name: component-data
          persistentVolumeClaim:
            claimName: component-service-pvc
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: component-service
  namespace: rig-and-barter
spec:
  selector:
    app: component-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: component-service-pvc
  namespace: rig-and-barter
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: component-service-secrets
  namespace: rig-and-barter
data:
  mongodb_connection_string: bW9uZ29kYjovL3JhYmFkbWluOnpuMnglMjY5U1BQVW0lMjVZa2dAbW9uZ29kYi5yaWctYW5kLWJhcnRlci5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9jb21wb25lbnQtc2VydmljZT9hdXRoU291cmNlPWFkbWlu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-service-config
  namespace: rig-and-barter
data:
  RB_STORAGE_DOCUMENT: "mongodb"
  SPRING_CLOUD_AWS_REGION_STATIC: "us-west-1"
  SPRING_CLOUD_AWS_STACK_AUTO: "false"
  AWS_S3_BUCKET-NAME: "rb-component-images-dev"

