apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  namespace: rig-and-barter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
        - name: listing-service
          image: cjshore1996/dev-listing-service:latest
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
                  name: common-config
            - name: TRANSACTION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: TRANSACTION_SERVICE_URL
                  name: common-config
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_SERVICE_URL
                  name: common-config
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE_URL
                  name: common-config
            - name: RB_EVENT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER
                  name: common-config
            - name: RB_EVENT_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER_URL
                  name: common-config
            - name: RB_STORAGE_FILE
              valueFrom:
                configMapKeyRef:
                  key: RB_STORAGE_FILE
                  name: listing-service-config
            - name: RB_STORAGE_DOCUMENT
              valueFrom:
                configMapKeyRef:
                  key: RB_STORAGE_DOCUMENT
                  name: listing-service-config
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_MONGODB_URI
                  name: listing-service-config
            - name: SPRING_CLOUD_AWS_REGION_STATIC
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_AWS_REGION_STATIC
                  name: listing-service-config
            - name: SPRING_CLOUD_AWS_STACK_AUTO
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_AWS_STACK_AUTO
                  name: listing-service-config
            - name: AWS_S3_BUCKET-NAME
              valueFrom:
                configMapKeyRef:
                  key: AWS_S3_BUCKET-NAME
                  name: listing-service-config
            - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_access_key
            - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_secret_key
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
  namespace: rig-and-barter
spec:
  selector:
    app: listing-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: rig-and-barter
data:
  aws_access_key: QUtJQVFSQUhURDI2RVRMS080SFk=
  aws_secret_key: YnRDWXBvS2VxbzJsRXN1eEtpdlExYm5nYVdIZ2xUV09jVmNQb3dxUQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: listing-service-config
  namespace: rig-and-barter
data:
  RB_STORAGE_FILE: "aws-s3"
  RB_STORAGE_DOCUMENT: "mongodb"
  SPRING_DATA_MONGODB_URI: "mongodb://root:password@mongodb.rig-and-barter.svc.cluster.local:27017/listing-service?authSource=admin"
  SPRING_CLOUD_AWS_REGION_STATIC: "us-west-1"
  SPRING_CLOUD_AWS_STACK_AUTO: "false"
  AWS_S3_BUCKET-NAME: "rb-listing-images-dev"

