{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "notification-service-secrets",
    "namespace": "dev-rig-and-barter",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "notification-service-secrets",
        "namespace": "dev-rig-and-barter",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "mongodb_connection_string": "AgDW9uCJC8u1KAoxIv/sl5NbmBL7R0nM6tZ/746mHQR6qT2Cw6yVr/kmjNJMobFCE/slB3661BEaasq+cCYoSYbiiUYqcX05ZJ7UG/8Wft8xsEPIaA63LvKBwile5eVW8LccJ6gVf9U619w3ua6eAbclatamZE3bbQGgEC8agLFg85KV5ukNX8qySVPozZp/nWr8VAed63OI4fp0zMl2gffWXJN+mkO501aLGGqGdcy/GvIa8MyK35Vo8nEI7neI3EFFt+7FPb+VPi7c6Jd6tNd4yeRk7Nopu3PNRDEYG9JDPlAdWmmnWu2iGtLbCXZi0IlIwAHz+pO++RNW+ZNEhzSPYsyjaq95DDWf8bV68Uq2IDtN/MzHMDy1yP55fO+SyLbC6OMpDq6IDNVVdz26Q8OHZZYtLCd2e6Fhw8Tb8x/GX4pkJpaBrTzMFaqrA2BaooMT/xnDp6AISQscfbnHNjK+5LbinM4DM3XSUs+H6XOePpMMzMTY8zp5Q6KBNng9VM6cbEKzcF3rTZqhLT+yqtCTSX2XWhGjikQ27IO6RWeIk2PwIEfVqVgV94WkMV77egdCOz07tFkS1k/m41MVvtx4lAPywMUWY5EmAnvh1biKCpYr9LTkm7XUsTAWL0J2vMohSzqpu1arVNwYNLC48YovpV3LW+HAzTB2TcVlcOOHkjvlfvqaixuUIVuNCmsZBTh3cfHN8C7Fbu338BlfzhzFs/j3f5KtbVk0MPzlmtTkg91jMym2V//BW8igJ0XBuqFgRzfnvOds45jY85o2kmhgt26nkFOtfYwMbnL+Dy+dwZWpH9eee4bA6wbMjaYm+AzeYY+KdvkCTHrMNfSXFl+xRec3ZvAXCFi7hw=="
    }
  }
}
