{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "keycloak-mysql-secrets",
    "namespace": "dev-rig-and-barter",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "keycloak-mysql-secrets",
        "namespace": "dev-rig-and-barter",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "mysql_password": "AgDA5Z7F9jlegrRVnO7uBh/G6x9EKaOItsYIXRA1bo34lmngwxyjh5woPdy/eoGrw0Cv/q1NVqDG7l0MRvEs+clmv+Ix2GSWfhvaAIra3EpuQ2pjuvJByWlm10nuOphgBMCyU53v1t6e1iRxdBrKgvGb2XiSC/9fIj13B+1TZTSSyz1eCJ13zlsGvZhoHxyQhodLia/7tjjAmEMFFA8YUpkO5JPJqmrGLRzpxrnTX9DFa+pinQWhH3TLAOFIqPpk53rMnU+CVSlF2eeDl4z7bLEB3GZEKG3o7snyyFrcWwp7RlU0vfXhrBAZ69+qfcyvFFbwTKYUbAo2MB2ymKXp1b7o1G8BXudI/diH3CTb1helgIsNwpNL3Dr8SzjbO5ZUJyoZoJlL7ongd/cAsnbUZLU4EMb/Q3PpRebThAKUR5++1OEB81MZWUOvguxJrX6haR0k7AvqQjTiK8qCRAaQaucmwlcs2GfbGAXBzW1hOvG4XYV94TYXzEIuBxZR7mzSLrLRfEtIHQoTcPG9kkvHyeuQTrzUsx2wYLf+cx3Wh8U9PeER/ULkk7SlVwET7ktku9xAnrSFPTKgfdCCDwkpslro+lOn5Xi6w3UiXAYvDp4lfUXFkDsIZRMk0wF7IeVINic17x7M1JgWxg5nSoGGl01tS6BMXNcAEeQyvv2pWlSxNCLt1HR0lzhCn5dT6EAxFH1Hawg+hYNsbZk3oT0wbOg=",
      "mysql_root_password": "AgCh4Tbkef15Udf8W4W17mV0aPOtPflZp86dIZ2WAnglTbrxrp1eFES7qVKJGCqMQA9Yhyz7QEqV58Ep45qN9yy195kJF9vX0Nbv06gQDVSK/cFqvEbtvGn8CvECa1+h6kF7pImyPG20Em8R6OV2boctWBuiCuyaE9rHBQVjHSwqKeVMN/LvpVh4U4dS+i5W9Z/kyjkuz8f3modGpyCB7MYVKUdrDEvwhta9RVDr9ePWdSdgE63aIE1FQPAWN1xD174GUGqeW3q6o9Xv7e6cefUV0GLRIg/Gvh5YejUXUAH8JwVELvAa31wik26VfZMjvR9IRkEUuArZexB9GwXhBqpc/2bHuvF77+Bb7Hdbt43kD0+Y4WuUlLPpHcGeN0RWqNGHQ3U4s2qdj4X8RBVBSrMlw4Cezz0VJVHcifvWLZGpfs7VZS1M7Uvx4VEDnisyYGobs/EceKjXJ43S1Qg/oKEvhaD+hktScD6ECmr7fpjKZieTi+Wcq6Ak9X9MXS0o4CJExcyXrTOfD6cP3sYbP/WawXT7XRi0hy3+wcFhp41hJD9dZC+6SmvB4qzgAthNiD+g0QmUjgnG4xhJKqQqm7jiV8rEyGVLMHD12xk+pWuJUMUEJKzm92cUt6Axet00h0McqdtcDhlxQzt/959/E3t4vmVfi42XtTuZfMK5BRhNcvX2L8W5a1IfS7v/5psm045K1BfO",
      "mysql_user": "AgDDCErdXDjNrtSRRVrEoVEH6xMbFNs7acd3sqTBz12k7twkDl3vEU9MPVGQN0aSVJnEt4ekQjEk2p/+2rvk+Ct/qfMlQFwcVuAKeke4wuqiUBSutfucHTeOv6d33ZDugBoT4+C3hroXq0reF/lQNEN71AwgJKaZdITX3i3nd/UkBjrRFZAR+PQERGkHOJMl2Zn9fKDfCyYfbo8EwmVQjP9i303MAT+Be4mAvq8iqYSx2Y9grmMLQicbRZcSd9VxYldfD7ilijYWZNfH2CQjfOBzcbp8nyc7T4yCtIiA3ER5K0Rp8qAJozNU09j4rGbSZSwS9PvSs2tq2/ZgM6XbZT2gpHYMnvdoCD7VLh9GuAI0Ch6EbLzkNvd6NEJuvWK47pM0Dl2ZbGiLBtBL/cfgYsEw8l5jP5seN3QxOeBQHC6aVPTuHfS2hl1ZhkOHx2ZGtQxEh/+8ts0ExEQWJbGrPywFEwUEhKs0dJlpgiDEsL+cY300+Re3fxSXqEtQuVMOOmtDCBwC961pH8PmsnrPrjy0QcYZsxtbKe/lQdcrIjvZEOY1VNTJnlH4WLPYxXupdQmznIJcdgWSmOB701598WaShEnzmLPatcrbhH3yDXeH+jL6AIN0iflfMaEowHHsOXSQ4sHcMpIHdUlUqQQCx4IJHRbVdVjUSl7u3x0PLBxuUb/as5V5u1dj5U+yPpOlmLlnaLPWxv9t7w=="
    }
  }
}
