apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: cjshore1996/new-payment-service:latest
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
                  name: common-config
            - name: RB_EVENT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER
                  name: common-config
            - name: RB_EVENT_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: RB_EVENT_BROKER_URL
                  name: common-config
            - name: RB_FRONT-END_URL
              valueFrom:
                configMapKeyRef:
                  key: RB_FRONT-END_URL
                  name: common-config
            - name: LISTING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: LISTING_SERVICE_URL
                  name: common-config
            - name: RB_STORAGE_RELATIONAL
              valueFrom:
                configMapKeyRef:
                  key: RB_STORAGE_RELATIONAL
                  name: payment-service-config
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: payment-service-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: payment-service-config
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_root_password
            - name: STRIPE_SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: stripe_secret_key
            - name: RB_STRIPE_FEE_PERCENT
              valueFrom:
                configMapKeyRef:
                  key: RB_STRIPE_FEE_PERCENT
                  name: payment-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: v1
data:
  mysql_root_password: bXlzcWw=
kind: Secret
metadata:
  name: mysql-secrets
---
apiVersion: v1
data:
  stripe_secret_key: U1RSSVBFX1NFQ1JFVF9LRVk9c2tfdGVzdF81MVBweENnRkFHczY5VkNGQW1nY29ENWxlNlRCNDZkREgwY2hGcXpWVzFWWTg3bUI1c0JEV0RiUEN3TkNyM0FtR3laWXRqczdEeXVXOWhibXpCVGdOelpwTzAwSUZPd2lMcU4=
kind: Secret
metadata:
  name: stripe-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  RB_STORAGE_RELATIONAL: "mysql"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/payment_service"
  RB_STRIPE_FEE_PERCENT: "0.07"