name: Clean Backend Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - demo
        - prod
      applicationsOnly:
        description: 'Only clean applications'
        required: true
        default: false
        type: boolean

jobs:
  clean-deployment-backend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - uses: actions-hub/kubectl@master
      if: ${{ inputs.applicationsOnly == false }}
      name: Clean Entire Backend
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: delete -f k8s/manifests/${{ inputs.environment }} --recursive
    - uses: actions-hub/kubectl@master
      if: ${{ inputs.applicationsOnly == true }}
      name: Clean Application Backend Only
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: delete -f k8s/manifests/${{ inputs.environment }}/applications --recursive