name: Clean Backend Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - demo
        - prod

jobs:
  clean-deployment-backend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - uses: actions-hub/kubectl@master
      name: Clean Backend
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: delete -f k8s/manifests/${{ inputs.environment }} --recursive