name: Deploy Backend To Kubernetes

on:
  pull_request:
#  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - uses: action/echo@v2
      with:
        message: "Deploying Backend to Kubernetes"

    - uses: actions/checkout@v4

    - uses: action/echo@v2
      with:
        message: "Checked out code"  

    - uses: actions-hub/kubectl@master
      name: Test Get Pods
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods --all-namespaces