name: Deploy Backend To Kubernetes

on:
  pull_request:
#  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - shell: bash
      run: |
        echo "Deploying Backend to Kubernetes"

    - uses: actions/checkout@v4

    - shell: bash
      run: |
        echo "Checked out code"
        echo "Getting current dir"
        ls -la

    - uses: actions-hub/kubectl@master
      name: Deploy Common Configs
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/dev/common --recursive

    - uses: actions-hub/kubectl@master
      name: Deploy Sealed Secrets Configs
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/dev/sealed-secrets --recursive

    - uses: actions-hub/kubectl@master
      name: Deploy Ingress Routes
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/dev/ingress --recursive

    - uses: actions-hub/kubectl@master
      name: Deploy Infrastructure Routes
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/dev/infrastructure --recursive

    - uses: actions-hub/kubectl@master
      name: Get status of pods
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods -n dev-rig-and-barter