name: Deploy Backend To Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions-hub/kubectl@master
      name: Test Get Pods
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods --all-namespaces