name: Deploy Backend To Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - demo
        - prod
      replicas:
        description: 'Replicas'
        required: true
        default: '1'
        type: number

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Insert Replica count on all files
      run: |
        find k8s/manifests/${{ inputs.environment }} -type f -name "*.yaml" -exec sed -i "s/__REPLICAS__/${{ inputs.replicas }}/g" {} \;
        
    - name: Replace Keycloak Access Key in Deployment
      run: |
        sed -i "s/__KEYCLOAK_SECRET__/${{ secrets.KEYCLOAK_SECRET }}/g" k8s/manifests/${{ inputs.environment }}/infrastructure/keycloak.yaml

    - uses: actions-hub/kubectl@master
      name: Deploy Common Configs
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/${{ inputs.environment }}/common --recursive

    - uses: actions-hub/kubectl@master
      name: Deploy Sealed Secrets
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/${{ inputs.environment }}/sealed-secrets --recursive

    - uses: actions-hub/kubectl@master
      name: Deploy Ingress Routes
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/${{ inputs.environment }}/ingress --recursive

    - uses: actions-hub/kubectl@master
      name: Deploy Infrastructure
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/${{ inputs.environment }}/infrastructure --recursive

    - name: Delay for 15 seconds to allow infrastructure to be initialized
      run: sleep 15

    - uses: actions-hub/kubectl@master
      name: Deploy Applications
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/manifests/${{ inputs.environment }}/applications --recursive