name: Deploy Backend To Kubernetes

on:
  pull_request:
#  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - shell: bash
      run: |
        echo "Deploying Backend to Kubernetes"

    - uses: actions/checkout@v4

    - shell: bash
      run: |
        echo "Checked out code"
        echo "Getting current dir"
        ls -la

    - uses: actions-hub/kubectl@master
      name: Deploy
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods --all-namespaces