# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Backend Images Manual

on:
  workflow_dispatch:
    inputs:
      imageLabel:
        description: 'Image Label'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - demo
          - prod

jobs:
  publish-development:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        brew install docker
        colima start

    - name: Build and Publish Images
      run: |
        mvn clean install -U -DdockerUsername=${{ vars.DOCKER_USERNAME }} -DdockerPassword=${{ secrets.DOCKER_PASSWORD }} -DimageVersion=latest
        mvn compile -DdockerUsername=${{ vars.DOCKER_USERNAME }} -DdockerPassword=${{ secrets.DOCKER_PASSWORD }} -DimageVersion=latest -DimageLabel=${{ inputs.imageLabel }} 
        mvn spring-boot:build-image -DdockerUsername=${{ vars.DOCKER_USERNAME }} -DdockerPassword=${{ secrets.DOCKER_PASSWORD }} -DimageVersion=latest -DimageLabel=${{ inputs.imageLabel }}  -Dskip=true
